name: PowerShell Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build PowerShell app
        shell: pwsh
        run: .\Driver.ps1 -Task ModuleBuild
