name: PowerShell Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install PowerShell 7
        uses: actions/setup-powershell@v2
        with:
          version: 7
      - name: Build PowerShell app
        run: pwsh -File ". ./Driver.ps1"
